name: datalab
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python>=3.12
  - sqlite
  - requests
  - pandas
  - xarray
  - dask
  - matplotlib
  - cartopy
  - seaborn
  - basemap
  - ipykernel
  - fsspec
  - 'libnetcdf<4.9'
  - pip:
    - cavapy
